#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošanai
git config --global user.name Armandsv11
git config --global user.email armandsv11@gmail.com
git commit -m "Class_$1"
git push origin main
